### ISSUE TITLE
Implementation: Directory type

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/common-workflow-language#201]
This is for @psaffrey-illumina, myself, and others to co-ordinate adding support for the Directory type as proposed in https://github.com/common-workflow-language/common-workflow-language/issues/172

> So I presume I need to modify the CommandLineTool.yml to add the directory option. I thought it should just be adding a similar entry to this:
https://github.com/common-workflow-language/common-workflow-language/blob/draft-4/draft-4/CommandLineTool.yml#L78
> but I'm a bit confused about this entry in the comments:
> "Define a file that must be placed in the designated output directory prior to executing the command line tool."
> I thought this was defining an input file but it talks about an *output* directory?

Here, FileDef is only used by http://www.commonwl.org/draft-3/CommandLineTool.html#CreateFileRequirement so the references to the output directory are correct.

For Draft-4 we will amend FileDef so we can use it to describe files where the name or content is changed.

Here is my understanding of what we need to do:

- [ ] Add `initialWorkDir` as an optional top-level entry for CommandLineTools
- [ ] Define the following fields for `initialWorkDir`: `class` (always `directory`), and `listing` (an array of `File`, expression, `FileDef`, or subdirectories)
- [ ] Update description of `FileDef`
- [ ] implement support for all of the above in `cwltool`
- [ ] write tests

**Comment by tetron** [comment]
The `Directory` type should go into Process.yml since it's shared between Workflows and Command Line Tools.

For background, the Directory concept here is being proposed to solve three specific problems: (a) on the input side, passing sets of input files preserving relative file/directory hierarchy (and being able to optimize for the common case where the directory already exists and just needs to be bind mounted), (b) for command line tools, being able to better describe how to initialize the output directory (a more general version of the existing CreateFileRequirement) and (c) command line tools being able to capture the the contents of the output directory (or some part of it) in a way that preserves relative file/directory hierarchy.

In particular, a Directory object is a "virtual" directory, the listing can contain files that are actually located in several different places (i.e. not actually from the same "physical" directory) which may have to be linked/staged/assembled in order to present to the command line tool.  This process of assembling the actual physical directory that will accessed by a tool should be the same for both directories as input parameters and initialWorkDir.

For (c), it may be sufficient to teach `glob` that when a path is a directory and not a file, produce a Directory object (so capturing the whole output directory would just be `glob: .`)

**Comment by psaffrey-illumina** [comment]
I just want to make sure I understand this. 

Firstly, we need a Directory type in Process.yml, something like this:

- name: Directory
  type: record
  docParent: "#CWLType"
  doc: |
    Represents a directory to present to a command line tool. This could be a virtual
    directory, made of files assembled from a number of concrete directories.
  fields:
    - name: class
      type:
        type: enum
        name: Directory_class
        symbols:
          - cwl:Directory
      jsonldPredicate:
        "_id": "@type"
        "_type": "@vocab"
      doc: Must be `Directory` to indicate this object describes a Directory.
    - name: path
      type: string
      doc: The path to the directory.
      jsonldPredicate:
        "_id": "cwl:path"
        "_type": "@id"
    - name: size
      type: ["null", long]
      doc: Optional directory size.

(should this be an item on your to-do list?)

The `initialWorkDir` part is less clear. Firstly, the name - isn't this a general name for passing directories into command line tools? And you might be able to pass more than one in the same command? The name seems to imply that you would build up one directory to expose and then `cd` there before the command start.

Secondly, I'm not quite sure where to add the option to pass a directory. It looks like it ought to be as part of the CommandLineBinding as a type like a File, but the only place I can see File referenced is in the text description. I guess I must be missing something...?

**Comment by psaffrey-illumina** [comment]
Any guidance on this? Sorry if these are stupid questions - I'd really like to contribute to this project but I might need a few pointers to get me started :)

**Comment by mr-c** [comment]
@psaffrey-illumina Let's just dive in and make commits to the branch and see what works.

**Comment by psaffrey-illumina** [comment]
I've committed some stuff to the branch but can't push.

**Comment by mr-c** [comment]
I've added you as a collaborator; try again?

On Thu, Apr 28, 2016 at 4:48 PM, psaffrey-illumina <notifications@github.com
> wrote:

> I've committed some stuff to the branch but can't push.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/common-workflow-language/common-workflow-language/issues/201#issuecomment-215450205>
>



-- 
Michael R. Crusoe                          michael.crusoe@gmail.com
Community Engineer                 Common Workflow Language project
*https://impactstory.org/u/0000-0002-2961-9670
<https://impactstory.org/u/0000-0002-2961-9670>*   +32 (0) 2 808 25 52
                                                    +1 480 627 9108

**Comment by psaffrey-illumina** [comment]
That worked, thanks.

**Comment by mr-c** [comment]
@psaffrey-illumina You can use `schema-salad-tool` from https://pypi.python.org/pypi/schema-salad / https://github.com/common-workflow-language/schema_salad to check your work

```
(env) mcrusoe@mrcdev:~/common-workflow-language$ schema-salad-tool draft-3/CommandLineTool-standalone.yml 
/home/mcrusoe/common-workflow-language/env/bin/schema-salad-tool 1.7.20160316203940
Schema `draft-3/CommandLineTool-standalone.yml` is valid
```
vs. your latest branch

```
(env) mcrusoe@mrcdev:~/common-workflow-language$ schema-salad-tool draft-4/CommandLineTool-standalone.yml 
/home/mcrusoe/common-workflow-language/env/bin/schema-salad-tool 1.7.20160316203940
Schema `draft-4/CommandLineTool-standalone.yml` failed link checking:
While checking object `https://w3id.org/cwl/cwl#InitialWorkingDirectory`
  While checking field `fields`
    While checking object `https://w3id.org/cwl/cwl#InitialWorkingDirectory/dirDef`
      Field `items` contains undefined reference to `https://w3id.org/cwl/File`
      Field `items` contains undefined reference to `https://w3id.org/cwl/Directory`
      While checking field `type`
        Field `items` contains undefined reference to `https://w3id.org/cwl/File`
        Field `items` contains undefined reference to `https://w3id.org/cwl/Directory`
```

**Comment by mr-c** [comment]
The problem here is lack of `#`, fixed by
```
diff --git a/draft-4/CommandLineTool.yml b/draft-4/CommandLineTool.yml
index c1c287b..1cd06e2 100644
--- a/draft-4/CommandLineTool.yml
+++ b/draft-4/CommandLineTool.yml
@@ -252,7 +252,7 @@ $graph:
     - name: dirDef
       type:
         type: "array"
-        items: [ "#FileDef", "File", "Directory" ]
+        items: [ "#FileDef", "#File", "#Directory" ]
       doc: list of files and/or directories
 ```

But now we have a new problem:
```
(env) mcrusoe@mrcdev:~/common-workflow-language$ schema-salad-tool draft-4/CommandLineTool-standalone.yml 
/home/mcrusoe/common-workflow-language/env/bin/schema-salad-tool 1.9.20160421133216
Traceback (most recent call last):
  File "/home/mcrusoe/common-workflow-language/env/bin/schema-salad-tool", line 11, in <module>
    sys.exit(main())
  File "/home/mcrusoe/common-workflow-language/env/local/lib/python2.7/site-packages/schema_salad/main.py", line 125, in main
    (schema_ctx, rdfs) = jsonld_context.salad_to_jsonld_context(schema_doc, metactx)
  File "/home/mcrusoe/common-workflow-language/env/local/lib/python2.7/site-packages/schema_salad/jsonld_context.py", line 154, in salad_to_jsonld_context
    process_type(t, g, context, defaultBase, namespaces, defaultPrefix)
  File "/home/mcrusoe/common-workflow-language/env/local/lib/python2.7/site-packages/schema_salad/jsonld_context.py", line 102, in process_type
    v = pred(t, i, fieldname, context, defaultPrefix, namespaces)
  File "/home/mcrusoe/common-workflow-language/env/local/lib/python2.7/site-packages/schema_salad/jsonld_context.py", line 62, in pred
    raise Exception("Predicate collision on %s, '%s' != '%s'" % (name, context[name], v))
Exception: Predicate collision on size, 'https://w3id.org/cwl/cwl#File/size' != 'https://w3id.org/cwl/cwl#Directory/size'
```

**Comment by mr-c** [comment]
@psaffrey-illumina If you drop the size parameter then the schema parses fine. We'll add it back later once the rest of the implementation is done.

**Comment by psaffrey-illumina** [comment]
What's next - the cwltool part? Still not sure about the initialWorkingDirectory side and whether that covers all the use-cases that @tetron raised above.

**Comment by mr-c** [comment]
@psaffrey-illumina I'm not seeing `initialWorkingDir` in the c-w-l draft-4 branch ..

**Comment by psaffrey-illumina** [comment]
https://github.com/common-workflow-language/common-workflow-language/blob/draft-4/draft-4/CommandLineTool.yml#L247

**Comment by mr-c** [comment]
@psaffrey-illumina okay, can we stick with `initialWorkDir` for now? And yes, we can start implementing this in cwltool now.

**Comment by psaffrey-illumina** [comment]
OK, I've changed the name as you suggest.

Should we work in a specific branch on cwltool? Where should we branch from?

**Comment by mr-c** [comment]
Yep, lets branch off of @tetron 's `draft-4-pa`

**Comment by psaffrey-illumina** [comment]
OK, I've branched from draft-4-pa to a branch checked-in here:

https://github.com/common-workflow-language/cwltool/tree/draft4-pa-201

I've used the convention of naming the branch after the issue. 

As sketched by @tetron, the changes are in 4 files. 

- in builder.py, I gather up any file inputs. There isn't any special logic here because I don't have to handle secondaryFiles as file inputs do.

- in draft2tool.py I pass these directories down to the PathMapper factory. I added these as an additional parameter rather than trying to conflate them with regular files.

- in pathmapper.py I largely reused the logic for creating a sensible mapping for the paths inside the container. I agonised a little over whether to try to keep the directory maps in a separate data structure but opted for lighter changes and a slightly more clunky storage mechanism by keeping a separate set member to keep track of which mapped paths are directories. I also added some comments as I was trying to understand the code - I hope this is OK.

- Finally, in job.py I added an additional validation condition to test for valid directories.

This is really just about passing in whole directories at this point. The more advanced case @tetron described where you stage a directory that might be created by assimilating files and directories from many locations isn't really covered yet.

It would be nice to create some test-cases - is there a set of test fixtures I can append to? Even if I can't grasp the subtleties necessary to create the staged directories this more user-facing task might be something I can help with.

**Comment by psaffrey-illumina** [comment]
To capture the meeting we had today about this feature:

- Work to continue on @tetron 's `stagefiles` branch:

https://github.com/common-workflow-language/cwltool/tree/stagefiles

- Need to add Directory support into PathMapper

- Add a test case here:

https://github.com/common-workflow-language/cwltool/tree/stagefiles/cwltool/schemas/draft-4/draft-4

- Think about gathering up the outputs for Directory types as well

**Comment by mr-c** [comment]
Done!
